platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

inputs:
  - name: cf-k8s-networking
  - name: bbl-state
  - name: kubeconfig

run:
  path: cf-k8s-networking/ci/tasks/k8s/install-cf-networking.sh

params:
  KUBECONFIG_CONTEXT:
  # - kubectl k8s context to use from kubeconfig
  BBL_STATE_DIR:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - If unspecified, uses the root of the `bbl-state` input

