---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: cf-system
data:
  config.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 15000
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            - filters:
                - name: envoy.tcp_proxy
                  config:
                    stat_prefix: ingress_tcp
                    cluster: upstream_80
                    access_log:
                      - name: envoy.file_access_log
                        config:
                          path: /dev/stdout
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 443
          filter_chains:
            - filters:
                - name: envoy.tcp_proxy
                  config:
                    stat_prefix: ingress_tcp
                    cluster: upstream_443
                    access_log:
                      - name: envoy.file_access_log
                        config:
                          path: /dev/stdout
      clusters:
        - name: upstream_80
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: round_robin
          load_assignment:
            cluster_name: upstream_80
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: istio-ingressgateway.istio-system
                          port_value: 80
                          protocol: TCP
        - name: upstream_443
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: round_robin
          load_assignment:
            cluster_name: upstream_443
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: istio-ingressgateway.istio-system
                          port_value: 443
                          protocol: TCP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-to-ingressgateway-proxy
  namespace: cf-system
  labels:
    app: node-to-ingressgateway-proxy
spec:
  selector:
    matchLabels:
      app: node-to-ingressgateway-proxy
  template:
    metadata:
      labels:
        app: node-to-ingressgateway-proxy
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
        - name: node-to-ingressgateway-proxy
          image: docker.io/envoyproxy/envoy:latest
          args: [ "-c", "/etc/envoy-config/config.yaml"]
          ports:
            - hostPort: 80
              containerPort: 80
            - hostPort: 443
              containerPort: 443
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy-config
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
