# Default values for cf-k8s-networking.
# This is a YAML-formatted file.

systemNamespace: cf-system
workloadsNamespace: cf-workloads

cfroutesync:
  version: latest
  # The values below are placeholders for configuring templates/cfroutesync-secret.yaml
  ccCA: 'path_to_cloud_controller_ca'
  ccBaseURL: 'https://api.example.com'
  uaaCA: 'path_to_uaa_ca'
  uaaBaseURL: 'https://uaa.example.com'
  clientName: 'uaaClientName'
  clientSecret: 'uaaClientSecret'
