#@data/values
---
istio_ports:
  control_plane_monitoring: 15014 #! used by Citadel, Citadel agent, Galley, Mixer, Pilot, Sidecar Injector
  grpc_server: 8060 #! used by Citadel
  pilot_health_checks: 15020 #! used by Ingress Gateway
  pilot_service_discovery: 15010 #! used by Pilot
  pilot_service_proxy_discovery_mtls: 15011 #! used by Pilot
  policy_telemetry: 9091 #! used by Mixer
  policy_telemetry_mtls: 15004 #! used by Mixer, Pilot
  proxy: 15090 #! used by Mixer
  sds_service_monitoring: 8080 #! used by Citadel agent
  sni_monitoring: 15443 #! used by Ingress and Egress Gateways.
  telemetry_prometheus: 42422 #! used by Mixer

