#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

istioVersion: 1.6.4
systemNamespace: cf-system
workloadsNamespace: cf-workloads

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:59bae5250aac171014bac055ef510f5818660d2fab70133618c83c514b12a577
upgradeSidecars:
  image: gcr.io/cf-networking-images/cf-k8s-networking/upgrade-sidecars@sha256:05735df07597bd0546e2b888da94016d241e46b572661ae15f8e362a923b76e9

service:
  externalPort: 80
