#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

istioVersion:
systemNamespace: cf-system
workloadsNamespace: cf-workloads

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:8ef88e0dcaa5228c2b325cf5296ff31666bd3e7525e994f4495ba4e8fc052ac8
upgradeSidecars:
  image: gcr.io/cf-networking-images/cf-k8s-networking/upgrade-sidecars@sha256:6a20de2fc2bf7835dfcbadf8f9ffa78bb7626097d6a6e384f54e984e1297423c

service:
  externalPort: 80
