platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

inputs:
  - name: cf-k8s-networking
  - name: cf-k8s-networking-ci
  - name: image-resource

outputs:
  - name: cf-k8s-networking-modified

run:
  path: cf-k8s-networking-ci/ci/tasks/docker/add-updated-sha.sh

params:
  COMPONENT_NAME: # e.g. cfroutesync, routecontroller
  GIT_COMMIT_USERNAME: "CF Networking Team CI Bot"
  GIT_COMMIT_EMAIL: "CF-Networking@pivotal.io"
