platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking-ci

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/create-gke-cluster.sh

params:
  CLUSTER_NAME:
  GCP_SERVICE_ACCOUNT_KEY:
  CLOUDSDK_COMPUTE_REGION: "us-west1"
  CLOUDSDK_COMPUTE_ZONE: "us-west1-a"
  ENABLE_IP_ALIAS: false
  NUM_NODES: 3 # This is the k8s default
  GCP_PROJECT: "cf-routing"
  MACHINE_TYPE: "n1-standard-4"
  EPHEMERAL_CLUSTER: true
  REGIONAL_CLUSTER: false
