platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking-ci
  - name: cf-for-k8s-master

outputs:
  - name: env-metadata

run:
  path: cf-k8s-networking-ci/ci/tasks/cf4k8s/install-cf-for-k8s.sh

params:
  CF_DOMAIN:
  CLUSTER_NAME:
  GCP_SERVICE_ACCOUNT_KEY:
  KPACK_GCR_ACCOUNT_KEY:
  CLOUDSDK_COMPUTE_REGION: "us-west1"
  CLOUDSDK_COMPUTE_ZONE: "us-west1-a"
  GCP_PROJECT: "cf-routing"
  SHARED_DNS_ZONE_NAME: "routing-lol"
